### PR TITLE
suggestions by deepak #13

### PR DESCRIPTION
**Pull request by apoorvagnihotri**
@sdeepaknarayanan When you get time do review the changes that I have made. Especially the change in `idw.py`.

### CODE REVIEW

**Comment by sdeepaknarayanan** [comment]
Can I know why we are adding XgBoost and Random Forest regressors? Are they related to Spatial Interpolation (We can have a base Neural Net Class too - a multi layer perceptron as well then). What's the motivation when we are dealing with classical interpolation methods?

**Comment by apoorvagnihotri** [comment]
We (Me and Prof. Nipun Batra) wanted us to try out these methods therefore
I had added them. They seem to perform better than the other methods
currently (see examples/air_dat.ipynb).

--
Apoorv Agnihotri
Computer Science Department
Final year Undergraduate
IIT Gandhinagar
apoorvagnihotri.github.io

Sent using Android.

**Comment by sdeepaknarayanan** [comment]
Can you make your data public? I can't see it in the branch for this pull request. Also, I think there was an issue with bspline (

**Comment by apoorvagnihotri** [comment]
The data is ~130 MB. I can send you a link.

Bspline issue can you be more specific?

--
Apoorv Agnihotri
Computer Science Department
Final year Undergraduate
IIT Gandhinagar
apoorvagnihotri.github.io

Sent using Android.

**Comment by sdeepaknarayanan** [comment]
You can directly use the data from the link I suppose? You can add a mention in the notebook else.  You have to add the find_closest.py script to utils. You haven’t I think. I get an import error when I run it. Add that commit and I’ll review once more. Check this: https://github.com/sustainability-lab/polire/tree/dev2/polire/utils

**Comment by apoorvagnihotri** [comment]
I'll update you with the link to data and the code soon. Thanks for
bringing this up!

--
Apoorv Agnihotri
Computer Science Department
Final year Undergraduate
IIT Gandhinagar
apoorvagnihotri.github.io

Sent using Android.

**Comment by sdeepaknarayanan** [comment]
I am merging it. I think the requested changes are minor and can be easily changed in future commits.

**Pull request merged**
