### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by apoorvagnihotri**
Added docs folder + added a setup.py file.

### CODE REVIEW

**Comment by sdeepaknarayanan** [comment]
What about pointwise prediction for BSpline? Doesn't SciPy support it?

**Comment by apoorvagnihotri** [comment]
@sdeepaknarayanan  
No SciPy doesn't support it.
I have to add support for it by finding point closest in the grid interpolated.

I think you can merge the pull request, all the other things are working. I will send another pull request when I am done with pointwise interpolation for BSpline.

Thanks!

**Comment by sdeepaknarayanan** [comment]
@apoorvagnihotri I think the change is minor. I'll merge once all of this is done at one go.

**Comment by sdeepaknarayanan** [comment]
Also, @apoorvagnihotri , in the comments, I'd ideally like you to mention 1st dimension and 2nd dimensions, instead of x1 dimension or x2 dimension (This causes confusion imo). interpolation can be for 3d too (we need to add support later i suppose)

**Comment by sdeepaknarayanan** [comment]
Also,can you set lims to None in _predict_grid for each of the interpolation techniques? (let it be optional -- we can interpolate by default on the entire range of values). If there are user provided args, then we can use your current version.

**Comment by sdeepaknarayanan** [comment]
I am merging without the changes that I requested.

**Comment by apoorvagnihotri** [comment]
@sdeepaknarayanan Sorry Deepak, was a bit caught up this weekend! I have updated the dev with the suggestions that you provided. I have also sent a pull request your way for the same, named `deepak-suggestions`.

Further, there was a suggestion from Prof Batra. to have the API as below, I have made the required change in your `idw.py` file: commit hash 1e2d2cccd79decf78d0a72a16b46e2f03ab2e5b0
```python
    def _predict_grid(self, x1lim, x2lim):
        lims = (*x1lim, *x2lim)
```
instead of
```python
    def _predict_grid(self, lims):
```

**Pull request merged**
